// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go [version omitted for reproducibility]
// 	protoc        [version omitted for reproducibility]
// source: guestservice.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Info struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalPorts    []*IPPort              `protobuf:"bytes,1,rep,name=local_ports,json=localPorts,proto3" json:"local_ports,omitempty"`
	Gui           *GUIInfo               `protobuf:"bytes,2,opt,name=gui,proto3" json:"gui,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Info) Reset() {
	*x = Info{}
	mi := &file_guestservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_guestservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_guestservice_proto_rawDescGZIP(), []int{0}
}

func (x *Info) GetLocalPorts() []*IPPort {
	if x != nil {
		return x.LocalPorts
	}
	return nil
}

func (x *Info) GetGui() *GUIInfo {
	if x != nil {
		return x.Gui
	}
	return nil
}

type GUIInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayServer string                 `protobuf:"bytes,1,opt,name=display_server,json=displayServer,proto3" json:"display_server,omitempty"`  // "X11", "Wayland", "none"
	SessionActive bool                   `protobuf:"varint,2,opt,name=session_active,json=sessionActive,proto3" json:"session_active,omitempty"` // Whether a GUI session is running
	Resolution    string                 `protobuf:"bytes,3,opt,name=resolution,proto3" json:"resolution,omitempty"`                             // Current display resolution, e.g., "1920x1080"
	IdleTimeMs    int64                  `protobuf:"varint,4,opt,name=idle_time_ms,json=idleTimeMs,proto3" json:"idle_time_ms,omitempty"`        // Milliseconds since last user activity
	Displays      []string               `protobuf:"bytes,5,rep,name=displays,proto3" json:"displays,omitempty"`                                 // Display names/identifiers (e.g., ":0", "wayland-0")
	Spice         *SpiceAgentInfo        `protobuf:"bytes,6,opt,name=spice,proto3" json:"spice,omitempty"`                                       // SPICE agent status for clipboard sharing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GUIInfo) Reset() {
	*x = GUIInfo{}
	mi := &file_guestservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GUIInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GUIInfo) ProtoMessage() {}

func (x *GUIInfo) ProtoReflect() protoreflect.Message {
	mi := &file_guestservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GUIInfo.ProtoReflect.Descriptor instead.
func (*GUIInfo) Descriptor() ([]byte, []int) {
	return file_guestservice_proto_rawDescGZIP(), []int{1}
}

func (x *GUIInfo) GetDisplayServer() string {
	if x != nil {
		return x.DisplayServer
	}
	return ""
}

func (x *GUIInfo) GetSessionActive() bool {
	if x != nil {
		return x.SessionActive
	}
	return false
}

func (x *GUIInfo) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *GUIInfo) GetIdleTimeMs() int64 {
	if x != nil {
		return x.IdleTimeMs
	}
	return 0
}

func (x *GUIInfo) GetDisplays() []string {
	if x != nil {
		return x.Displays
	}
	return nil
}

func (x *GUIInfo) GetSpice() *SpiceAgentInfo {
	if x != nil {
		return x.Spice
	}
	return nil
}

type SpiceAgentInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentInstalled bool                   `protobuf:"varint,1,opt,name=agent_installed,json=agentInstalled,proto3" json:"agent_installed,omitempty"` // Whether spice-vdagent is installed
	AgentRunning   bool                   `protobuf:"varint,2,opt,name=agent_running,json=agentRunning,proto3" json:"agent_running,omitempty"`       // Whether spice-vdagentd service is active
	VportExists    bool                   `protobuf:"varint,3,opt,name=vport_exists,json=vportExists,proto3" json:"vport_exists,omitempty"`          // Whether virtio console port exists
	ClipboardReady bool                   `protobuf:"varint,4,opt,name=clipboard_ready,json=clipboardReady,proto3" json:"clipboard_ready,omitempty"` // Whether clipboard sharing is functional
	ErrorMessage   string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`        // Error details if clipboard is not ready
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SpiceAgentInfo) Reset() {
	*x = SpiceAgentInfo{}
	mi := &file_guestservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpiceAgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpiceAgentInfo) ProtoMessage() {}

func (x *SpiceAgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_guestservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpiceAgentInfo.ProtoReflect.Descriptor instead.
func (*SpiceAgentInfo) Descriptor() ([]byte, []int) {
	return file_guestservice_proto_rawDescGZIP(), []int{2}
}

func (x *SpiceAgentInfo) GetAgentInstalled() bool {
	if x != nil {
		return x.AgentInstalled
	}
	return false
}

func (x *SpiceAgentInfo) GetAgentRunning() bool {
	if x != nil {
		return x.AgentRunning
	}
	return false
}

func (x *SpiceAgentInfo) GetVportExists() bool {
	if x != nil {
		return x.VportExists
	}
	return false
}

func (x *SpiceAgentInfo) GetClipboardReady() bool {
	if x != nil {
		return x.ClipboardReady
	}
	return false
}

func (x *SpiceAgentInfo) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type Event struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Time              *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	AddedLocalPorts   []*IPPort              `protobuf:"bytes,2,rep,name=added_local_ports,json=addedLocalPorts,proto3" json:"added_local_ports,omitempty"`
	RemovedLocalPorts []*IPPort              `protobuf:"bytes,3,rep,name=removed_local_ports,json=removedLocalPorts,proto3" json:"removed_local_ports,omitempty"`
	Errors            []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_guestservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_guestservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_guestservice_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Event) GetAddedLocalPorts() []*IPPort {
	if x != nil {
		return x.AddedLocalPorts
	}
	return nil
}

func (x *Event) GetRemovedLocalPorts() []*IPPort {
	if x != nil {
		return x.RemovedLocalPorts
	}
	return nil
}

func (x *Event) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type IPPort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"` // tcp, udp
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPPort) Reset() {
	*x = IPPort{}
	mi := &file_guestservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPPort) ProtoMessage() {}

func (x *IPPort) ProtoReflect() protoreflect.Message {
	mi := &file_guestservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPPort.ProtoReflect.Descriptor instead.
func (*IPPort) Descriptor() ([]byte, []int) {
	return file_guestservice_proto_rawDescGZIP(), []int{4}
}

func (x *IPPort) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *IPPort) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *IPPort) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Inotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountPath     string                 `protobuf:"bytes,1,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inotify) Reset() {
	*x = Inotify{}
	mi := &file_guestservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inotify) ProtoMessage() {}

func (x *Inotify) ProtoReflect() protoreflect.Message {
	mi := &file_guestservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inotify.ProtoReflect.Descriptor instead.
func (*Inotify) Descriptor() ([]byte, []int) {
	return file_guestservice_proto_rawDescGZIP(), []int{5}
}

func (x *Inotify) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *Inotify) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type TunnelMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"` // tcp, udp
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	GuestAddr     string                 `protobuf:"bytes,4,opt,name=guest_addr,json=guestAddr,proto3" json:"guest_addr,omitempty"`
	UdpTargetAddr string                 `protobuf:"bytes,5,opt,name=udp_target_addr,json=udpTargetAddr,proto3" json:"udp_target_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelMessage) Reset() {
	*x = TunnelMessage{}
	mi := &file_guestservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelMessage) ProtoMessage() {}

func (x *TunnelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_guestservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelMessage.ProtoReflect.Descriptor instead.
func (*TunnelMessage) Descriptor() ([]byte, []int) {
	return file_guestservice_proto_rawDescGZIP(), []int{6}
}

func (x *TunnelMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TunnelMessage) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *TunnelMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TunnelMessage) GetGuestAddr() string {
	if x != nil {
		return x.GuestAddr
	}
	return ""
}

func (x *TunnelMessage) GetUdpTargetAddr() string {
	if x != nil {
		return x.UdpTargetAddr
	}
	return ""
}

var File_guestservice_proto protoreflect.FileDescriptor

const file_guestservice_proto_rawDesc = "" +
	"\n" +
	"\x12guestservice.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"L\n" +
	"\x04Info\x12(\n" +
	"\vlocal_ports\x18\x01 \x03(\v2\a.IPPortR\n" +
	"localPorts\x12\x1a\n" +
	"\x03gui\x18\x02 \x01(\v2\b.GUIInfoR\x03gui\"\xdc\x01\n" +
	"\aGUIInfo\x12%\n" +
	"\x0edisplay_server\x18\x01 \x01(\tR\rdisplayServer\x12%\n" +
	"\x0esession_active\x18\x02 \x01(\bR\rsessionActive\x12\x1e\n" +
	"\n" +
	"resolution\x18\x03 \x01(\tR\n" +
	"resolution\x12 \n" +
	"\fidle_time_ms\x18\x04 \x01(\x03R\n" +
	"idleTimeMs\x12\x1a\n" +
	"\bdisplays\x18\x05 \x03(\tR\bdisplays\x12%\n" +
	"\x05spice\x18\x06 \x01(\v2\x0f.SpiceAgentInfoR\x05spice\"\xcf\x01\n" +
	"\x0eSpiceAgentInfo\x12'\n" +
	"\x0fagent_installed\x18\x01 \x01(\bR\x0eagentInstalled\x12#\n" +
	"\ragent_running\x18\x02 \x01(\bR\fagentRunning\x12!\n" +
	"\fvport_exists\x18\x03 \x01(\bR\vvportExists\x12'\n" +
	"\x0fclipboard_ready\x18\x04 \x01(\bR\x0eclipboardReady\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\xbd\x01\n" +
	"\x05Event\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x123\n" +
	"\x11added_local_ports\x18\x02 \x03(\v2\a.IPPortR\x0faddedLocalPorts\x127\n" +
	"\x13removed_local_ports\x18\x03 \x03(\v2\a.IPPortR\x11removedLocalPorts\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\"H\n" +
	"\x06IPPort\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"X\n" +
	"\aInotify\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x01 \x01(\tR\tmountPath\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"\x96\x01\n" +
	"\rTunnelMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"guest_addr\x18\x04 \x01(\tR\tguestAddr\x12&\n" +
	"\x0fudp_target_addr\x18\x05 \x01(\tR\rudpTargetAddr2\xc8\x01\n" +
	"\fGuestService\x12(\n" +
	"\aGetInfo\x12\x16.google.protobuf.Empty\x1a\x05.Info\x12-\n" +
	"\tGetEvents\x12\x16.google.protobuf.Empty\x1a\x06.Event0\x01\x121\n" +
	"\vPostInotify\x12\b.Inotify\x1a\x16.google.protobuf.Empty(\x01\x12,\n" +
	"\x06Tunnel\x12\x0e.TunnelMessage\x1a\x0e.TunnelMessage(\x010\x01B/Z-github.com/lima-vm/lima/v2/pkg/guestagent/apib\x06proto3"

var (
	file_guestservice_proto_rawDescOnce sync.Once
	file_guestservice_proto_rawDescData []byte
)

func file_guestservice_proto_rawDescGZIP() []byte {
	file_guestservice_proto_rawDescOnce.Do(func() {
		file_guestservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guestservice_proto_rawDesc), len(file_guestservice_proto_rawDesc)))
	})
	return file_guestservice_proto_rawDescData
}

var file_guestservice_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_guestservice_proto_goTypes = []any{
	(*Info)(nil),                  // 0: Info
	(*GUIInfo)(nil),               // 1: GUIInfo
	(*SpiceAgentInfo)(nil),        // 2: SpiceAgentInfo
	(*Event)(nil),                 // 3: Event
	(*IPPort)(nil),                // 4: IPPort
	(*Inotify)(nil),               // 5: Inotify
	(*TunnelMessage)(nil),         // 6: TunnelMessage
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_guestservice_proto_depIdxs = []int32{
	4,  // 0: Info.local_ports:type_name -> IPPort
	1,  // 1: Info.gui:type_name -> GUIInfo
	2,  // 2: GUIInfo.spice:type_name -> SpiceAgentInfo
	7,  // 3: Event.time:type_name -> google.protobuf.Timestamp
	4,  // 4: Event.added_local_ports:type_name -> IPPort
	4,  // 5: Event.removed_local_ports:type_name -> IPPort
	7,  // 6: Inotify.time:type_name -> google.protobuf.Timestamp
	8,  // 7: GuestService.GetInfo:input_type -> google.protobuf.Empty
	8,  // 8: GuestService.GetEvents:input_type -> google.protobuf.Empty
	5,  // 9: GuestService.PostInotify:input_type -> Inotify
	6,  // 10: GuestService.Tunnel:input_type -> TunnelMessage
	0,  // 11: GuestService.GetInfo:output_type -> Info
	3,  // 12: GuestService.GetEvents:output_type -> Event
	8,  // 13: GuestService.PostInotify:output_type -> google.protobuf.Empty
	6,  // 14: GuestService.Tunnel:output_type -> TunnelMessage
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_guestservice_proto_init() }
func file_guestservice_proto_init() {
	if File_guestservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guestservice_proto_rawDesc), len(file_guestservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_guestservice_proto_goTypes,
		DependencyIndexes: file_guestservice_proto_depIdxs,
		MessageInfos:      file_guestservice_proto_msgTypes,
	}.Build()
	File_guestservice_proto = out.File
	file_guestservice_proto_goTypes = nil
	file_guestservice_proto_depIdxs = nil
}
